import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="bg-slate-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-evenly p-16">
        <div className="font-sans mb-4 container mx-auto">
          <h1 className="text-3xl font-extralight text-emerald-100">
            Ryan Gregory
          </h1>
          <h1 className="text-xl font-thin text-red-200">Web Developer</h1>
          <h1 className="text-md text-slate-300">Atlanta, GA</h1>
          <a
            className="text-violet-300 text-sm  hover:text-amber-200 hover:text-md"
            href="mailto: Ryan.middleFiddle@gmail.com"
          >
            Ryan.middleFiddle@gmail.com
          </a>
        </div>
        <div className="font-mono text-sky-100 flex flex-col container mx-auto">
          <p className="pb-4">
            I&apos;m a web developer focused enabling contractors, artists,
            artisans, small businesses and freelancers to organize their
            operations and simplify their communication with clients.
          </p>

          <p className="pb-4">
            I work primarily with Next JS because it&apos;s expressiveness and
            flexibility allow me to delivery rich, optimized, accessible content
            easily. I am looking for opportunities to deepen my knowledge of Web
            Components and WASM/WASI. In addition to my current stack, I would
            would also welcome opportunitites to work with Qwik, Polymer,
            SolidJS or Elixir/Phoenix (I ❤ THE BEAM).
          </p>

          <p className="pb-4">
            I also teach people how to play music, most often on the violin, and
            I play viola with the Atlanta Opera.
          </p>
        </div>
      </main>

      {/*       <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
